include_guard(DIRECTORY)
if (UNIX)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        target_compile_options(${PROJECT_NAME} PRIVATE -stdlib=libc++)
        target_link_libraries(${PROJECT_NAME} PRIVATE c++ c++abi unwind)
        target_link_options(${PROJECT_NAME} PRIVATE -fuse-ld=${LLD})
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        if (NOT BUILD_DYNAMIC)
            target_link_options(${PROJECT_NAME} PRIVATE -static-libgcc -static-libstdc++)
        endif()

        if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS "9.0.0")
            target_link_options(${PROJECT_NAME} PRIVATE -lstdc++fs)
        endif()
    else()
        message(FATAL_ERROR "Either Clang or GCC is supported.")
    endif()
else()
    if (NOT CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        message(FATAL_ERROR "Only MSVC is supported.")
    endif()
endif()
