include_guard(DIRECTORY)
if (UNIX)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND LLVM_TOOLCHAIN)
        target_compile_options(${PROJECT_NAME} PRIVATE -stdlib=libc++)
        target_link_libraries(${PROJECT_NAME} PRIVATE c++ c++abi unwind)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR NOT LLVM_TOOLCHAIN)
        set(MINIMUM_CLANG_VERSION "7.0.0")
        if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS MINIMUM_CLANG_VERSION)
            message(WARNING "Clang v${CMAKE_CXX_COMPILER_VERSION} is not supported. Minimum version is ${MINIMUM_CLANG_VERSION}.")
        endif()

        if (NOT BUILD_DYNAMIC)
            target_link_options(${PROJECT_NAME} PRIVATE -static-libgcc -static-libstdc++)
        endif()

        if ((CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS "9.0.0") OR NOT LLVM_TOOLCHAIN)
            target_link_options(${PROJECT_NAME} PRIVATE -lstdc++fs)
        endif()
    else()
        message(FATAL_ERROR "Either Clang or GCC is supported.")
    endif()
else()
    if (NOT CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        message(FATAL_ERROR "Only MSVC is supported.")
    endif()
endif()
